### ISSUE TITLE
error C2589: '(': illegal token on right side of '::' msvc 2019 compile error for latest commit

### ISSUE THREAD

**Issue by omortie** [KDAB/KDDockWidgets#266]
Hi, I'm using KDDockWidgets as a 3rdparty lib in my application and it's one of my git submodules
the latest commit will not get build by MSVC 2019 compiler and the errors are these:

..\libs\3rdparty\KDDockWidgets\src\private\FloatingWindow.cpp(647): error C2589: '(': illegal token on right side of '::'
..\libs\3rdparty\KDDockWidgets\src\private\FloatingWindow.cpp(647): error C2062: type 'unknown-type' unexpected
..\libs\3rdparty\KDDockWidgets\src\private\FloatingWindow.cpp(647): error C2059: syntax error: ')'

I've managed to build this library successfully before for at least 1 year, but now it broke the build since f1e19ec59c7db4ced8a11265a040a63eac30e527 commit

**Comment by winterz** [comment]
fixed in 0adb130d4b2bc9223fbe6269b1cbb7c22d6da98c
